Lesson_05/WebApplication1/WebApplication1/Areas/AdminPanel/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Lesson_05/WebApplication1/WebApplication1/Controllers/ChatController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication.Controllers
{
    public class ChatController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Lesson_05/WebApplication1/WebApplication1/Controllers/PeopleController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication1.Models.People;
using WebApplication1.Services;
using WebApplication1.Services.Abstract;

namespace WebApplication1.Controllers
{
    public class PeopleController : Controller
    {
        readonly IWebPeopleService _peopleService;
        readonly IMemoryCache _cache;

        public PeopleController(
            IWebPeopleService peopleService,
            IMemoryCache cache)
        {
            _peopleService = peopleService;
            _cache = cache;
        }

        // Default
        // [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        [ResponseCache(Location = ResponseCacheLocation.Any, Duration = 2 * 60, NoStore = false)]
        public IActionResult Index()
        {
            List<PersonModel> people = null;

            // Caching in memory
            //if (!_cache.TryGetValue("people", out people))
            //{
            //    people = _peopleService.GetAllPeople();
            //    var options = new MemoryCacheEntryOptions();
            //    options.SetAbsoluteExpiration(TimeSpan.FromMinutes(2));
            //    // добавление данных в кеш
            //    _cache.Set("people", people, options);
            //}
            people = _peopleService.GetAllPeople();

            return View(new PeopleIndexViewModel
            {
                People = people,
                MaxPerson = people.FirstOrDefault(p => p.Birth.Ticks == people.Min((p) => p.Birth.Ticks)),
                MinPerson = people.FirstOrDefault(p => p.Birth.Ticks == people.Max((p) => p.Birth.Ticks)),
            });
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CreatePersonModel person)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Model is not valid!");
                return View(person);
            }
            _peopleService.CreateNewPerson(person);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(Guid? id)
        {
            if (id is null || _peopleService.GetPersonById((Guid)id) is null)
            {
                return BadRequest("Person was not found");
            }
            _peopleService.RemovePersonById((Guid)id);
            return RedirectToAction("Index");
        }

        public IActionResult Edit(Guid? id)
        {
            if (id is null || _peopleService.GetPersonById((Guid)id) is null)
            {
                return BadRequest("Person was not found");
            }
            return View(_peopleService.GetPersonById((Guid)id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(PersonModel person)
        {
            if (_peopleService.GetPersonById((Guid)person.Id) is null)
            {
                return BadRequest("Person was not found");
            }

            _peopleService.UpdatePerson(person);
            return View(_peopleService.GetPersonById(person.Id));
        }

        public IActionResult Detail(Guid? id)
        {
            if (id is null || _peopleService.GetPersonById((Guid)id) is null)
            {
                return BadRequest("Person was not found");
            }
            return View(_peopleService.GetPersonById((Guid)id));
        }
    }
}

Lesson_05/WebApplication1/WebApplication1/Views/Shared/_Layout.cshtml
@inject WebApplication1.Utils.AppUtils Utils
@using System.Globalization
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Chat" asp-action="Index">Chat</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="People" asp-action="Index">People</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="AdminPanel" asp-controller="Admin" asp-action="Index">AdminPanel</a>
                        </li>
                    </ul>
                </div>
                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Language (@CultureInfo.CurrentCulture.Name)
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        @foreach (var lang in Utils.AvailableLanguages)
                        {
                            <a class="dropdown-item dropdown-item-lang" data-lang="@lang" href="#">@lang</a>
                        }
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>